begin;
set client_min_messages to error;
set client_encoding = 'UTF8';

-- country codes used mainly for foreign key constraint on people.country
-- from http://en.wikipedia.org/wiki/iso_3166-1_alpha-2 
-- no need for any api to update, insert, or delete from this table.
create table countries (
	code character(2) not null primary key,
	name text
);

create table people (
	id integer primary key generated by default as identity,
	email text unique check (email ~ '\A\S+@\S+\.\S+\Z'),
	name text not null check (length(name) > 0),
	city text,
	state text,
	country char(2) references countries(code)
);
commit;
