set client_min_messages to error;
set client_encoding = 'UTF8';

create table items (
	id integer primary key generated by default as identity,
	name text not null unique,
	price numeric,
	weight numeric
);

create table invoices (
	id integer primary key generated by default as identity,
	person_id integer not null references people(id),
	order_date date not null default current_date,
	payment_date date,
	payment_info text,
	subtotal numeric,
	shipping numeric,
	total numeric,
	country char(2) references countries(code),
	address text,
	ship_date date,
	ship_info text
);
create index on invoices(person_id);
create index unshipped on invoices(payment_date, ship_date, address);

create table lineitems (
	id integer primary key generated by default as identity,
	invoice_id integer not null references invoices(id) on delete cascade,
	item_id integer not null references items(id) on delete restrict,
	quantity smallint not null default 1 check (quantity > 0),
	price numeric,
	unique(invoice_id, item_id)
);
create index on lineitems(invoice_id);

create table shipchart (
	id integer primary key generated by default as identity,
	country char(2) references countries(code),
	weight numeric not null, -- up to this (invoice.weight <= shipchart.weight)
	cost numeric not null
);
create index on shipchart(country, weight);

